// Generated by gencpp from file my_class_pkg/MyActionGoal.msg
// DO NOT EDIT!


#ifndef MY_CLASS_PKG_MESSAGE_MYACTIONGOAL_H
#define MY_CLASS_PKG_MESSAGE_MYACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_class_pkg
{
template <class ContainerAllocator>
struct MyActionGoal_
{
  typedef MyActionGoal_<ContainerAllocator> Type;

  MyActionGoal_()
    : object_name()  {
    }
  MyActionGoal_(const ContainerAllocator& _alloc)
    : object_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_name_type;
  _object_name_type object_name;





  typedef boost::shared_ptr< ::my_class_pkg::MyActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_class_pkg::MyActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MyActionGoal_

typedef ::my_class_pkg::MyActionGoal_<std::allocator<void> > MyActionGoal;

typedef boost::shared_ptr< ::my_class_pkg::MyActionGoal > MyActionGoalPtr;
typedef boost::shared_ptr< ::my_class_pkg::MyActionGoal const> MyActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_class_pkg::MyActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_class_pkg::MyActionGoal_<ContainerAllocator1> & lhs, const ::my_class_pkg::MyActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.object_name == rhs.object_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_class_pkg::MyActionGoal_<ContainerAllocator1> & lhs, const ::my_class_pkg::MyActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_class_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_class_pkg::MyActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_class_pkg::MyActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_class_pkg::MyActionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f12226348d323c2e5b2031b3da53f1b";
  }

  static const char* value(const ::my_class_pkg::MyActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f12226348d323c2ULL;
  static const uint64_t static_value2 = 0xe5b2031b3da53f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_class_pkg/MyActionGoal";
  }

  static const char* value(const ::my_class_pkg::MyActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string object_name #定义目标\n"
;
  }

  static const char* value(const ::my_class_pkg::MyActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_class_pkg::MyActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_class_pkg::MyActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CLASS_PKG_MESSAGE_MYACTIONGOAL_H
