// Generated by gencpp from file my_class_pkg/MyServiceMsg.msg
// DO NOT EDIT!


#ifndef MY_CLASS_PKG_MESSAGE_MYSERVICEMSG_H
#define MY_CLASS_PKG_MESSAGE_MYSERVICEMSG_H

#include <ros/service_traits.h>


#include <my_class_pkg/MyServiceMsgRequest.h>
#include <my_class_pkg/MyServiceMsgResponse.h>


namespace my_class_pkg
{

struct MyServiceMsg
{

typedef MyServiceMsgRequest Request;
typedef MyServiceMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MyServiceMsg
} // namespace my_class_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_class_pkg::MyServiceMsg > {
  static const char* value()
  {
    return "9cc62145209219f185101e72e3ae5c65";
  }

  static const char* value(const ::my_class_pkg::MyServiceMsg&) { return value(); }
};

template<>
struct DataType< ::my_class_pkg::MyServiceMsg > {
  static const char* value()
  {
    return "my_class_pkg/MyServiceMsg";
  }

  static const char* value(const ::my_class_pkg::MyServiceMsg&) { return value(); }
};


// service_traits::MD5Sum< ::my_class_pkg::MyServiceMsgRequest> should match
// service_traits::MD5Sum< ::my_class_pkg::MyServiceMsg >
template<>
struct MD5Sum< ::my_class_pkg::MyServiceMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_class_pkg::MyServiceMsg >::value();
  }
  static const char* value(const ::my_class_pkg::MyServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_class_pkg::MyServiceMsgRequest> should match
// service_traits::DataType< ::my_class_pkg::MyServiceMsg >
template<>
struct DataType< ::my_class_pkg::MyServiceMsgRequest>
{
  static const char* value()
  {
    return DataType< ::my_class_pkg::MyServiceMsg >::value();
  }
  static const char* value(const ::my_class_pkg::MyServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_class_pkg::MyServiceMsgResponse> should match
// service_traits::MD5Sum< ::my_class_pkg::MyServiceMsg >
template<>
struct MD5Sum< ::my_class_pkg::MyServiceMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_class_pkg::MyServiceMsg >::value();
  }
  static const char* value(const ::my_class_pkg::MyServiceMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_class_pkg::MyServiceMsgResponse> should match
// service_traits::DataType< ::my_class_pkg::MyServiceMsg >
template<>
struct DataType< ::my_class_pkg::MyServiceMsgResponse>
{
  static const char* value()
  {
    return DataType< ::my_class_pkg::MyServiceMsg >::value();
  }
  static const char* value(const ::my_class_pkg::MyServiceMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_CLASS_PKG_MESSAGE_MYSERVICEMSG_H
