// Generated by gencpp from file my_class_pkg/MyServiceMsgResponse.msg
// DO NOT EDIT!


#ifndef MY_CLASS_PKG_MESSAGE_MYSERVICEMSGRESPONSE_H
#define MY_CLASS_PKG_MESSAGE_MYSERVICEMSGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_class_pkg
{
template <class ContainerAllocator>
struct MyServiceMsgResponse_
{
  typedef MyServiceMsgResponse_<ContainerAllocator> Type;

  MyServiceMsgResponse_()
    : output(0)  {
    }
  MyServiceMsgResponse_(const ContainerAllocator& _alloc)
    : output(0)  {
  (void)_alloc;
    }



   typedef int64_t _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MyServiceMsgResponse_

typedef ::my_class_pkg::MyServiceMsgResponse_<std::allocator<void> > MyServiceMsgResponse;

typedef boost::shared_ptr< ::my_class_pkg::MyServiceMsgResponse > MyServiceMsgResponsePtr;
typedef boost::shared_ptr< ::my_class_pkg::MyServiceMsgResponse const> MyServiceMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator1> & lhs, const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator1> & lhs, const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_class_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaf29e6e649dbd18239f4c3f12579de7";
  }

  static const char* value(const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaf29e6e649dbd18ULL;
  static const uint64_t static_value2 = 0x239f4c3f12579de7ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_class_pkg/MyServiceMsgResponse";
  }

  static const char* value(const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 output # 回复\n"
"\n"
;
  }

  static const char* value(const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyServiceMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_class_pkg::MyServiceMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<int64_t>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CLASS_PKG_MESSAGE_MYSERVICEMSGRESPONSE_H
