// Generated by gencpp from file my_class_pkg/MyServiceMsgRequest.msg
// DO NOT EDIT!


#ifndef MY_CLASS_PKG_MESSAGE_MYSERVICEMSGREQUEST_H
#define MY_CLASS_PKG_MESSAGE_MYSERVICEMSGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_class_pkg
{
template <class ContainerAllocator>
struct MyServiceMsgRequest_
{
  typedef MyServiceMsgRequest_<ContainerAllocator> Type;

  MyServiceMsgRequest_()
    : input(0)  {
    }
  MyServiceMsgRequest_(const ContainerAllocator& _alloc)
    : input(0)  {
  (void)_alloc;
    }



   typedef int64_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MyServiceMsgRequest_

typedef ::my_class_pkg::MyServiceMsgRequest_<std::allocator<void> > MyServiceMsgRequest;

typedef boost::shared_ptr< ::my_class_pkg::MyServiceMsgRequest > MyServiceMsgRequestPtr;
typedef boost::shared_ptr< ::my_class_pkg::MyServiceMsgRequest const> MyServiceMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator1> & lhs, const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator1> & lhs, const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_class_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efb1911a9ea9163151d70e4586fa0801";
  }

  static const char* value(const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefb1911a9ea91631ULL;
  static const uint64_t static_value2 = 0x51d70e4586fa0801ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_class_pkg/MyServiceMsgRequest";
  }

  static const char* value(const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 input # 查询\n"
;
  }

  static const char* value(const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyServiceMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_class_pkg::MyServiceMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<int64_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CLASS_PKG_MESSAGE_MYSERVICEMSGREQUEST_H
