(cl:defpackage my_class_pkg-msg
  (:use )
  (:export
   "<MYACTIONACTION>"
   "MYACTIONACTION"
   "<MYACTIONACTIONFEEDBACK>"
   "MYACTIONACTIONFEEDBACK"
   "<MYACTIONACTIONGOAL>"
   "MYACTIONACTIONGOAL"
   "<MYACTIONACTIONRESULT>"
   "MYACTIONACTIONRESULT"
   "<MYACTIONFEEDBACK>"
   "MYACTIONFEEDBACK"
   "<MYACTIONGOAL>"
   "MYACTIONGOAL"
   "<MYACTIONRESULT>"
   "MYACTIONRESULT"
   "<MYMESSAGE>"
   "MYMESSAGE"
  ))

