; Auto-generated. Do not edit!


(cl:in-package my_class_pkg-msg)


;//! \htmlinclude MyActionGoal.msg.html

(cl:defclass <MyActionGoal> (roslisp-msg-protocol:ros-message)
  ((object_name
    :reader object_name
    :initarg :object_name
    :type cl:string
    :initform ""))
)

(cl:defclass MyActionGoal (<MyActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MyActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MyActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_class_pkg-msg:<MyActionGoal> is deprecated: use my_class_pkg-msg:MyActionGoal instead.")))

(cl:ensure-generic-function 'object_name-val :lambda-list '(m))
(cl:defmethod object_name-val ((m <MyActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_class_pkg-msg:object_name-val is deprecated.  Use my_class_pkg-msg:object_name instead.")
  (object_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MyActionGoal>) ostream)
  "Serializes a message object of type '<MyActionGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'object_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'object_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MyActionGoal>) istream)
  "Deserializes a message object of type '<MyActionGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'object_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'object_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MyActionGoal>)))
  "Returns string type for a message object of type '<MyActionGoal>"
  "my_class_pkg/MyActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MyActionGoal)))
  "Returns string type for a message object of type 'MyActionGoal"
  "my_class_pkg/MyActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MyActionGoal>)))
  "Returns md5sum for a message object of type '<MyActionGoal>"
  "2f12226348d323c2e5b2031b3da53f1b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MyActionGoal)))
  "Returns md5sum for a message object of type 'MyActionGoal"
  "2f12226348d323c2e5b2031b3da53f1b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MyActionGoal>)))
  "Returns full string definition for message of type '<MyActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string object_name #定义目标~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MyActionGoal)))
  "Returns full string definition for message of type 'MyActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string object_name #定义目标~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MyActionGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'object_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MyActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MyActionGoal
    (cl:cons ':object_name (object_name msg))
))
