; Auto-generated. Do not edit!


(cl:in-package my_class_pkg-msg)


;//! \htmlinclude MyActionResult.msg.html

(cl:defclass <MyActionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass MyActionResult (<MyActionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MyActionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MyActionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_class_pkg-msg:<MyActionResult> is deprecated: use my_class_pkg-msg:MyActionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <MyActionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_class_pkg-msg:success-val is deprecated.  Use my_class_pkg-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MyActionResult>) ostream)
  "Serializes a message object of type '<MyActionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MyActionResult>) istream)
  "Deserializes a message object of type '<MyActionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MyActionResult>)))
  "Returns string type for a message object of type '<MyActionResult>"
  "my_class_pkg/MyActionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MyActionResult)))
  "Returns string type for a message object of type 'MyActionResult"
  "my_class_pkg/MyActionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MyActionResult>)))
  "Returns md5sum for a message object of type '<MyActionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MyActionResult)))
  "Returns md5sum for a message object of type 'MyActionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MyActionResult>)))
  "Returns full string definition for message of type '<MyActionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success #定义结果~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MyActionResult)))
  "Returns full string definition for message of type 'MyActionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success #定义结果~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MyActionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MyActionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MyActionResult
    (cl:cons ':success (success msg))
))
