; Auto-generated. Do not edit!


(cl:in-package my_class_pkg-msg)


;//! \htmlinclude MyActionFeedback.msg.html

(cl:defclass <MyActionFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:float
    :initform 0.0))
)

(cl:defclass MyActionFeedback (<MyActionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MyActionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MyActionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_class_pkg-msg:<MyActionFeedback> is deprecated: use my_class_pkg-msg:MyActionFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <MyActionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_class_pkg-msg:progress-val is deprecated.  Use my_class_pkg-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MyActionFeedback>) ostream)
  "Serializes a message object of type '<MyActionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MyActionFeedback>) istream)
  "Deserializes a message object of type '<MyActionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MyActionFeedback>)))
  "Returns string type for a message object of type '<MyActionFeedback>"
  "my_class_pkg/MyActionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MyActionFeedback)))
  "Returns string type for a message object of type 'MyActionFeedback"
  "my_class_pkg/MyActionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MyActionFeedback>)))
  "Returns md5sum for a message object of type '<MyActionFeedback>"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MyActionFeedback)))
  "Returns md5sum for a message object of type 'MyActionFeedback"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MyActionFeedback>)))
  "Returns full string definition for message of type '<MyActionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 progress #定义反馈消息~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MyActionFeedback)))
  "Returns full string definition for message of type 'MyActionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 progress #定义反馈消息~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MyActionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MyActionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MyActionFeedback
    (cl:cons ':progress (progress msg))
))
